import type { Phase, Flow, ActiveFlow, VendorConvo, Vendor } from '@/types'

export const PHASES: Phase[] = [
  // Phase id stays 'rfq' for backwards compatibility with the backend phase
  // mapping; the user-facing label reflects what actually happens in this
  // phase — vendor discovery. RFQs go out during NEG.
  { id: 'rfq',  label: 'DISC', long: 'Vendor Discovery' },
  { id: 'neg',  label: 'NEG',  long: 'Negotiation' },
  { id: 'po',   label: 'PO',   long: 'Purchase Order' },
  { id: 'grn',  label: 'GRN',  long: 'Goods Receipt' },
  { id: 'inv',  label: 'INV',  long: 'Invoice Match' },
  { id: 'done', label: 'DONE', long: 'Complete' },
]

export const FLOWS: Flow[] = [
  {
    id: 'PR-2026-0418',
    summary: 'CNC spindle motors, 7.5kW × 24',
    requester: 'm.okafor',
    opened: '2026-05-02',
    days: 7,
    phase: 'neg',
    state: 'AWAITING_VENDOR_RESPONSE',
    vendors: 4,
    target: 186_400,
    needsAction: true,
    actionLabel: 'Approve final selection',
    note: 'Vendor 0421 escalated terms — approval needed to proceed.',
  },
  {
    id: 'PR-2026-0417',
    summary: 'Stainless 316L sheet, 1.5mm × 320 m²',
    requester: 'r.huang',
    opened: '2026-05-01',
    days: 8,
    phase: 'po',
    state: 'AWAITING_PO_ACK',
    vendors: 1,
    target: 78_900,
    needsAction: false,
  },
  {
    id: 'PR-2026-0416',
    summary: 'Industrial lubricant, ISO VG 68 × 800 L',
    requester: 'a.patel',
    opened: '2026-04-29',
    days: 10,
    phase: 'grn',
    state: 'PARTIAL_RECEIPT',
    vendors: 1,
    target: 12_400,
    needsAction: true,
    actionLabel: 'Review shortfall',
    note: '3 of 8 drums missing on delivery; vendor disputing.',
  },
  {
    id: 'PR-2026-0415',
    summary: 'PLC controllers, Allen-Bradley 5380 × 12',
    requester: 'm.okafor',
    opened: '2026-04-27',
    days: 12,
    phase: 'inv',
    state: 'THREE_WAY_MISMATCH',
    vendors: 1,
    target: 56_200,
    needsAction: true,
    actionLabel: 'Resolve invoice mismatch',
    note: 'Invoice exceeds PO by $1,420 — vendor surcharge unverified.',
  },
  {
    id: 'PR-2026-0414',
    summary: 'Bearings, SKF 6205-2RS × 2,400',
    requester: 'l.becker',
    opened: '2026-04-25',
    days: 14,
    phase: 'done',
    state: 'COMPLETE',
    vendors: 1,
    target: 9_600,
    needsAction: false,
  },
  {
    id: 'PR-2026-0413',
    summary: 'Hydraulic hose assemblies, SAE 100R2 × 60',
    requester: 'r.huang',
    opened: '2026-04-24',
    days: 15,
    phase: 'rfq',
    state: 'COLLECTING_QUOTES',
    vendors: 6,
    target: 14_200,
    needsAction: false,
  },
  {
    id: 'PR-2026-0412',
    summary: 'Polycarbonate sheet, clear 6mm × 80',
    requester: 'a.patel',
    opened: '2026-04-22',
    days: 17,
    phase: 'neg',
    state: 'COUNTER_OFFER_REVIEW',
    vendors: 3,
    target: 22_800,
    needsAction: false,
  },
  {
    id: 'PR-2026-0411',
    summary: 'Servo drives, Siemens SINAMICS V90 × 6',
    requester: 'm.okafor',
    opened: '2026-04-20',
    days: 19,
    phase: 'walked',
    state: 'WALKED_AWAY',
    vendors: 0,
    target: 41_200,
    needsAction: false,
    walked: true,
  },
  {
    id: 'PR-2026-0410',
    summary: 'Pneumatic cylinders, Festo DSBC × 40',
    requester: 'l.becker',
    opened: '2026-04-18',
    days: 21,
    phase: 'done',
    state: 'COMPLETE',
    vendors: 1,
    target: 18_700,
    needsAction: false,
  },
]

export const ACTIVE_FLOW: ActiveFlow = {
  id: 'PR-2026-0418',
  title: 'CNC spindle motors, 7.5kW × 24',
  requester: 'm.okafor',
  costCenter: 'PROD-EAST-04',
  opened: '2026-05-02 09:14',
  target: 186_400,
  needBy: '2026-05-22',
  spec: 'Siemens 1FK7-equivalent, IP65, water-cooled. Compatible with HAAS VF-2 retrofit.',
  phaseDurations: {
    rfq: '1d 04h',
    neg: '5d 18h',
    po: null,
    grn: null,
    inv: null,
    done: null,
  },
  currentPhase: 'neg',
  vendors: [
    {
      id: 'V-0218',
      name: 'Heinrich Tooling GmbH',
      country: 'DE',
      round: '3 / 3',
      state: 'AWAITING_VENDOR_RESPONSE',
      status: 'NEGOTIATING',
      latest: 188_220,
      delta: 1_820,
      moq: 24,
      lead: '14d',
      thread: [
        { who: 'them', what: '$201,840', meta: 'Round 1 — initial quote, 21d lead' },
        { who: 'us',   what: '$181,900', meta: 'Round 1 — counter, target -10%, 14d ask' },
        { who: 'them', what: '$192,300', meta: 'Round 2 — 14d lead conceded, +tooling fee' },
        { who: 'us',   what: '$185,200', meta: 'Round 2 — counter, tooling fee waived' },
        { who: 'them', what: '$188,220', meta: 'Round 3 — best & final, IP65 upgrade incl.' },
      ],
    },
    {
      id: 'V-0421',
      name: 'Apex Servo Industrial',
      country: 'US',
      round: '2 / 3',
      state: 'ESCALATED_TO_BUYER',
      status: 'NEGOTIATING',
      latest: 184_960,
      delta: -1_440,
      moq: 24,
      lead: '18d',
      escalated: true,
      thread: [
        { who: 'them', what: '$198,400', meta: 'Round 1 — quote, 24d lead' },
        { who: 'us',   what: '$179,000', meta: 'Round 1 — counter, target -10%' },
        { who: 'them', what: '$184,960', meta: 'Round 2 — counter, requests NET-15 instead of NET-30' },
      ],
    },
    {
      id: 'V-0719',
      name: 'Yamashita Precision Co.',
      country: 'JP',
      round: '3 / 3',
      state: 'OFFER_LOCKED',
      status: 'WON',
      latest: 182_640,
      delta: -3_760,
      moq: 24,
      lead: '16d',
      thread: [
        { who: 'them', what: '$194,200', meta: 'Round 1 — quote, premium build' },
        { who: 'us',   what: '$178,000', meta: 'Round 1 — counter, target -8%' },
        { who: 'them', what: '$186,500', meta: 'Round 2 — 16d lead, NET-30' },
        { who: 'us',   what: '$182,000', meta: 'Round 2 — counter, asks 24m warranty' },
        { who: 'them', what: '$182,640', meta: 'Round 3 — accepted, 24m warranty incl.' },
      ],
    },
    {
      id: 'V-1102',
      name: 'Brightfield Motion',
      country: 'CN',
      round: '1 / 3',
      state: 'WALKED_AWAY',
      status: 'WALKED_AWAY',
      latest: null,
      delta: null,
      moq: 50,
      lead: '32d',
      thread: [
        { who: 'them', what: '$172,000', meta: 'Round 1 — quote, MOQ 50, 32d lead' },
        { who: 'us',   what: '—',        meta: 'Round 1 — disqualified, MOQ exceeds need by 108%' },
      ],
    },
  ],
  activity: [
    { ts: '14:32', ag: 'NegotiationAgent', det: 'Sent counter to V-0218 at $185,200 (round 2).' },
    { ts: '14:18', ag: 'NegotiationAgent', det: 'Received best & final from V-0719: $182,640.' },
    { ts: '13:55', ag: 'EscalationAgent',  det: 'V-0421 requested NET-15 — outside policy. Escalated.' },
    { ts: '13:40', ag: 'NegotiationAgent', det: 'V-1102 disqualified: MOQ 50 exceeds requirement.' },
    { ts: '11:02', ag: 'RFQAgent',         det: 'Closed RFQ window. 4 of 7 vendors responded.' },
    { ts: '09:18', ag: 'SpecAgent',        det: 'Validated spec against HAAS VF-2 retrofit catalog.' },
    { ts: '09:14', ag: 'IntakeAgent',      det: 'PR opened by m.okafor — auto-categorized as Class B.' },
  ],
}

export const VENDOR_CONVO: VendorConvo = {
  vendor: { id: 'V-0421', name: 'Apex Servo Industrial', country: 'US', tier: 'Tier 2', mssa: 'MSSA-2024-318' },
  pr: 'PR-2026-0418',
  outcome: 'IN_PROGRESS — ESCALATED',
  messages: [
    {
      ts: '2026-05-03 09:02:14',
      from: 'BuyerRFQAgent', to: 'ApexQuoteBot',
      type: 'RFQ_INVITE',
      phase: 'rfq',
      payload: {
        sku: 'CNC-SPINDLE-7K5-IP65',
        qty: 24,
        target_price_usd: 186_400,
        need_by: '2026-05-22',
      },
    },
    {
      ts: '2026-05-03 14:18:02',
      from: 'ApexQuoteBot', to: 'BuyerRFQAgent',
      type: 'QUOTE',
      phase: 'rfq',
      payload: {
        unit_price_usd: 8_267,
        total_usd: 198_408,
        lead_time_days: 24,
        terms: 'NET-30',
        warranty: '12m',
      },
    },
    {
      ts: '2026-05-04 10:45:00',
      from: 'BuyerNegotiationAgent', to: 'ApexQuoteBot',
      type: 'COUNTER_OFFER',
      phase: 'neg',
      locked: true,
      payload: {
        target_total_usd: 179_000,
        target_lead_days: 16,
        terms: 'NET-30',
        rationale: 'V-0719 quoted $194,200 / 16d. Aligning to median.',
      },
    },
    {
      ts: '2026-05-05 11:12:33',
      from: 'ApexQuoteBot', to: 'BuyerNegotiationAgent',
      type: 'COUNTER_RESPONSE',
      phase: 'neg',
      payload: {
        unit_price_usd: 7_707,
        total_usd: 184_960,
        lead_time_days: 18,
        terms: 'NET-15',
        warranty: '12m',
      },
    },
    {
      ts: '2026-05-05 11:14:08',
      from: 'PolicyAgent', to: 'BuyerNegotiationAgent',
      type: 'STATE_MISMATCH_ERROR',
      phase: 'neg',
      error: true,
      payload: {
        rule: 'PAYMENT_TERMS_FLOOR',
        expected: 'NET-30',
        received: 'NET-15',
        action: 'BLOCK_AUTO_ACCEPT',
      },
    },
    {
      ts: '2026-05-05 11:14:12',
      from: 'EscalationAgent', to: 'm.okafor@procuforge.io',
      type: 'ESCALATION',
      phase: 'neg',
      payload: {
        reason: 'Vendor terms outside policy floor',
        decision_required: 'ACCEPT / REJECT / RENEGOTIATE',
        timeout: '24h',
      },
    },
  ],
}

export const VENDORS: Vendor[] = [
  { id: 'V-0218', name: 'Heinrich Tooling GmbH',       country: 'DE', tier: 'Tier-2', pr: 'PR-2026-0418', last: '14:32',     state: 'NEGOTIATING',     unread: 0, msgs: 12 },
  { id: 'V-0421', name: 'Apex Servo Industrial',        country: 'US', tier: 'Tier-2', pr: 'PR-2026-0418', last: '13:55',     state: 'ESCALATED',       unread: 2, msgs: 9  },
  { id: 'V-0719', name: 'Yamashita Precision Co.',      country: 'JP', tier: 'Tier-1', pr: 'PR-2026-0418', last: '14:18',     state: 'OFFER_LOCKED',    unread: 0, msgs: 14 },
  { id: 'V-1102', name: 'Brightfield Motion',           country: 'CN', tier: 'Tier-3', pr: 'PR-2026-0418', last: 'yesterday', state: 'WALKED_AWAY',     unread: 0, msgs: 4  },
  { id: 'V-0344', name: 'Northbridge Steel & Alloy',    country: 'US', tier: 'Tier-1', pr: 'PR-2026-0417', last: '11:22',     state: 'AWAITING_PO_ACK', unread: 1, msgs: 7  },
  { id: 'V-0512', name: 'Tribology Direct LLC',         country: 'US', tier: 'Tier-3', pr: 'PR-2026-0416', last: '09:08',     state: 'DELIVERY_DISPUTE',unread: 3, msgs: 18 },
  { id: 'V-0828', name: 'Rockwell Distribution Partners',country: 'US', tier: 'Tier-1', pr: 'PR-2026-0415', last: '2d ago',   state: 'INVOICE_DISPUTE', unread: 1, msgs: 22 },
  { id: 'V-0917', name: 'Nordic Bearings AB',           country: 'SE', tier: 'Tier-2', pr: 'PR-2026-0414', last: '4d ago',    state: 'CLOSED',          unread: 0, msgs: 11 },
  { id: 'V-0102', name: 'Hyperline Hydraulics',         country: 'US', tier: 'Tier-2', pr: 'PR-2026-0413', last: '5h ago',    state: 'QUOTING',         unread: 0, msgs: 3  },
  { id: 'V-0285', name: 'PolyGlobe Materials',          country: 'DE', tier: 'Tier-2', pr: 'PR-2026-0412', last: '8h ago',    state: 'NEGOTIATING',     unread: 0, msgs: 8  },
]
