import type { WorkflowRow, WorkflowSummary } from '@/types/workflow'

export const mockWorkflows: WorkflowRow[] = [
  {
    id: 'PR-2026-0418',
    product: 'CNC spindle motors, 7.5kW × 24',
    requestedBy: 'm.okafor',
    requestedAt: '2026-05-02',
    phase: 'NEG',
    currentState: 'AWAITING_VENDOR_RESPONSE',
    vendors: 4,
    days: 7,
    needsAction: true,
    actionLabel: 'Approve final selection',
  },
  {
    id: 'PR-2026-0417',
    product: 'Stainless 316L sheet, 1.5mm × 320 m²',
    requestedBy: 'r.huang',
    requestedAt: '2026-05-01',
    phase: 'PO',
    currentState: 'AWAITING_PO_ACK',
    vendors: 1,
    days: 8,
    needsAction: false,
    actionLabel: null,
  },
  {
    id: 'PR-2026-0416',
    product: 'Industrial lubricant, ISO VG 68 × 800 L',
    requestedBy: 'a.patel',
    requestedAt: '2026-04-29',
    phase: 'GRN',
    currentState: 'PARTIAL_RECEIPT',
    vendors: 1,
    days: 10,
    needsAction: true,
    actionLabel: 'Review shortfall',
  },
  {
    id: 'PR-2026-0415',
    product: 'PLC controllers, Allen-Bradley 5380 × 12',
    requestedBy: 'm.okafor',
    requestedAt: '2026-04-27',
    phase: 'INV',
    currentState: 'THREE_WAY_MISMATCH',
    vendors: 1,
    days: 12,
    needsAction: true,
    actionLabel: 'Resolve invoice mismatch',
  },
  {
    id: 'PR-2026-0414',
    product: 'Bearings, SKF 6205-2RS × 2,400',
    requestedBy: 'l.becker',
    requestedAt: '2026-04-25',
    phase: 'DONE',
    currentState: 'COMPLETE',
    vendors: 1,
    days: 14,
    needsAction: false,
    actionLabel: null,
  },
  {
    id: 'PR-2026-0413',
    product: 'Hydraulic hose assemblies, SAE 100R2 × 60',
    requestedBy: 'r.huang',
    requestedAt: '2026-04-24',
    phase: 'RFQ',
    currentState: 'COLLECTING_QUOTES',
    vendors: 6,
    days: 15,
    needsAction: false,
    actionLabel: null,
  },
  {
    id: 'PR-2026-0412',
    product: 'Polycarbonate sheet, clear 6mm × 80',
    requestedBy: 'a.patel',
    requestedAt: '2026-04-22',
    phase: 'NEG',
    currentState: 'COUNTER_OFFER_REVIEW',
    vendors: 3,
    days: 17,
    needsAction: false,
    actionLabel: null,
  },
]

export const mockSummary: WorkflowSummary = {
  total: 9,
  inProgress: 6,
  needsAction: 3,
  completed: 2,
  walkedAway: 1,
}
