"""Top-level PR lifecycle status (see ``docs/request_status.md``)."""

from __future__ import annotations

from enum import StrEnum


class PrStatus(StrEnum):
    """All documented ``pr_status`` values for session state and APIs."""

    INITIATED = "INITIATED"
    VENDORS_DISCOVERED = "VENDORS_DISCOVERED"
    NO_VENDORS_DISCOVERED = "NO_VENDORS_DISCOVERED"
    NEGOTIATION_IN_PROGRESS = "NEGOTIATION_IN_PROGRESS"
    NEGOTIATION_COMPLETED = "NEGOTIATION_COMPLETED"
    NO_VENDOR_AVAILABLE = "NO_VENDOR_AVAILABLE"
    VENDOR_SELECTED = "VENDOR_SELECTED"
    AWAITING_USER_APPROVAL = "AWAITING_USER_APPROVAL"
    PO_ISSUED = "PO_ISSUED"
    PO_ACKNOWLEDGED = "PO_ACKNOWLEDGED"
    PO_REJECTED = "PO_REJECTED"
    AWAITING_DELIVERY = "AWAITING_DELIVERY"
    GOODS_RECEIVED = "GOODS_RECEIVED"
    AWAITING_INVOICE = "AWAITING_INVOICE"
    INVOICE_UNDER_VERIFICATION = "INVOICE_UNDER_VERIFICATION"
    INVOICE_CORRECTION_PENDING = "INVOICE_CORRECTION_PENDING"
    INVOICE_VERIFIED = "INVOICE_VERIFIED"
    READY_FOR_PAYMENT = "READY_FOR_PAYMENT"
    COMPLETED = "COMPLETED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"
