"""Canonical ADK session.state keys for the buyer workflow."""

PRODUCT_KEY = "product"
REQUEST_KEY = "request"
PLANNER_PLAN_KEY = "current_plan"
VENDOR_OFFERS_KEY = "vendor_offers"
PR_STATUS_KEY = "pr_status"
PREVIOUS_PR_STATUS_KEY = "previous_pr_status"
SELECTED_VENDOR_KEY = "selected_vendor"
NEGOTIATION_CONFIG_KEY = "negotiation_config"
